version: '3'
services:
  app:
    build: docker/php
    container_name: myfinalprogect2_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.21
    container_name: myfinalprogect2_nginx
    ports:
      - 26073:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/myfinalprogect2.local.conf:/etc/nginx/conf.d/myfinalprogect2.local.conf

    depends_on:
      - app
  db:
    image: mysql:8.0.23
    ports:
      - 33063:3306
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: myfinalprogect2_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myfinalprogect2_db
      MYSQL_USER: myfinalprogect2_user
      MYSQL_PASSWORD: myfinalprogect2_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
